### ISSUE TITLE
Not supported for updated Idea versions.

### ISSUE THREAD

**Issue by bhadkenaresh841** [gayanper/idea-spring-tools#5]
Hey man, can you add support for the latest 2021 version of IntelliJ Idea builds as I love this plugin. Also tried compiling myself for the latest version but unable to get the required dependencies from bintray as those are password protected.

**Comment by gayanper** [comment]
Please try the build available at https://dl.cloudsmith.io/public/gap/ist/raw/files/idea-spring-tools-1.2.0.zip It is upload to plugin marketplace as well and pending verification.

**Comment by gayanper** [comment]
The release is available at https://github.com/gayanper/idea-spring-tools/releases/tag/1.2.1
